FROM zabbix/zabbix-web-apache-pgsql:alpine-3.4-latest
#Roteamento para vpn
RUN sed -i '/#!\/bin\/bash/a if [ ! -z $NET_ROUTE ] && [ ! -z $VPN_SERVER_IP ]; then route add -net $NET_ROUTE gw $VPN_SERVER_IP; fi' /usr/bin/docker-entrypoint.sh &&\
    echo 'LoadModule rewrite_module modules/mod_rewrite.so' > .htaccess &&\
    echo 'RewriteEngine On' >> .htaccess &&\
    echo 'RewriteCond %{HTTPS} off' >> .htaccess &&\
    echo 'RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]' >> .htaccess
